[package]
name = "cargotom"
version = "0.13.4"
edition = "2021"

[dependencies]
taplo = {git = "https://github.com/frederik-uni/taplo"}
tower-lsp = "0.20.0"
git2 = { version = "0.19.0", features = ["vendored-openssl"] }
serde_json = "1"
trie-rs = "0.4.2"
clap = { version = "4.5.18", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"]}
reqwest = {version = "0.12.7", features = ["json"]}
urlencoding = "2.1.3"
webbrowser = "1.0.2"
# tame-index = {version = "0.13.2", features = ["sparse"]}
